src/Isen.Dotnet.Web/Models/ErrorViewModel.cs
using System;

namespace Isen.Dotnet.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Isen.Dotnet.Web/Controllers/BaseController.cs
using System.Collections.Generic;
using System.Linq;
using Isen.Dotnet.Library.Context;
using Isen.Dotnet.Library.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Isen.Dotnet.Web.Controllers
{
    public abstract class BaseController<T> : Controller
        where T : BaseEntity
    {
        protected readonly ILogger<BaseController<T>> Logger;
        protected readonly ApplicationDbContext Context;

        protected BaseController(
            ILogger<BaseController<T>> logger,
            ApplicationDbContext context)
        {
            Logger = logger;
            Context = context;
            Logger.LogDebug("BaseController<T>/constructeur");
        }

        protected virtual IQueryable<T> BaseQuery() => 
            Context.Set<T>().AsQueryable();
 
        // https://localhost:5001/[Controller]/Index
        [HttpGet] // facultatif car GET par défaut
        public virtual IActionResult Index()
        {       
            var entities = BaseQuery().ToList();
            return View(entities);
        }

        // https://localhost:5001/[Controller]/Edit/42
        [HttpGet]
        public virtual IActionResult Edit(int? id)
        {
            // Pas d'id : formulaire vierge (création)
            if (id == null) return View();
            // Rechercher la personne ayant l'Id <id>
            return View(
                // Contexte > Liste des personnes : prendre la 1ère entité qui...
                BaseQuery().FirstOrDefault(
                    // ... correspond à ce prédicat de recherche
                    e => e.Id == id));
        }

        // https://localhost:5001/[Controller]/Edit/ (objet en POST)
        [HttpPost]
        public virtual IActionResult Edit(T entity)
        {
            if (entity == null) return RedirectToAction("Index");
            // Créer l'entité
            if (entity?.Id == 0) Context.Set<T>().Add(entity);
            // Mise à jour de l'entité
            else Context.Set<T>().Update(entity);
            // Sauvegarder le contexte
            Context.SaveChanges();
            // Renvoyer à la liste
            return RedirectToAction("Index");
        }

        // https://localhost:5001/[Controller]/Delete/42
        [HttpGet]
        public virtual IActionResult Delete(int id)
        {
            // Trouver la personne à supprimer
            var entity = Context.Set<T>()
                .FirstOrDefault(e => e.Id == id);
            // Supprimer l'entité
            if (entity != null) Context.Set<T>().Remove(entity);
            // Sauvegarder
            Context.SaveChanges();
            // Renvoyer vers la liste
            return RedirectToAction("Index");
        }

        public virtual IEnumerable<T> GetData() => 
            BaseQuery().ToList();
    }
}

src/Isen.Dotnet.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Isen.Dotnet.Web.Models;

namespace Isen.Dotnet.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Ajax()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Isen.Dotnet.Web/Controllers/PersonController.cs
using System;
using System.Linq;
using Isen.Dotnet.Library.Context;
using Isen.Dotnet.Library.Model;
using Isen.Dotnet.Library.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;


namespace Isen.Dotnet.Web.Controllers
{
    public class PersonController : BaseController<Person>
    {
        public PersonController(
            ILogger<PersonController> logger,
            ApplicationDbContext context) : base(logger, context)
        {
        }               

        // Exemple d'override de la query : liste les personnes
        protected override IQueryable<Person> BaseQuery() =>
            base.BaseQuery()
            .Include(pers => pers.Service)
            .Include("PersonRoles.Role");

    }
}

src/Isen.Dotnet.Web/Controllers/RoleController.cs
using System;
using System.Linq;
using Isen.Dotnet.Library.Context;
using Isen.Dotnet.Library.Model;
using Isen.Dotnet.Library.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;

namespace Isen.Dotnet.Web.Controllers
{
    public class RoleController : BaseController<Role>
    {
        public RoleController(
            ILogger<RoleController> logger,
            ApplicationDbContext context) : base(logger, context)
        {
        }

        protected override IQueryable<Role> BaseQuery() =>
            base.BaseQuery()
                .Include("PersonRoles.Person");
    }
}

src/Isen.Dotnet.Web/Controllers/ServiceController.cs
using System;
using System.Linq;
using Isen.Dotnet.Library.Context;
using Isen.Dotnet.Library.Model;
using Isen.Dotnet.Library.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Isen.Dotnet.Web.Controllers
{
    public class ServiceController : BaseController<Service>
    {
        public ServiceController(
            ILogger<ServiceController> logger,
            ApplicationDbContext context) : base(logger, context)
        {
        }
    }
}

src/Isen.Dotnet.Web/Views/Home/Ajax.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Vue Ajax</h1>
    <div id="result">Chargement en cours...</div>
</div>

src/Isen.Dotnet.Web/Views/Home/Index.cshtml
@{
    var welcomeMessage = $"Bienvenue, il est {DateTime.Now.ToShortTimeString()}";
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>@welcomeMessage</p>
</div>

src/Isen.Dotnet.Web/Views/Person/Edit.cshtml
@{
    ViewData["Title"] = "Edition d'un personne";
}
@using Isen.Dotnet.Library.Model;
@using Isen.Dotnet.Library.Context;
@model Person;
@inject ApplicationDbContext _context;

@{
    var dateTimeString = "";
    if (Model?.DateOfBirth != null) 
        dateTimeString = Model.DateOfBirth.Value.ToString("dd/MM/yyyy");
}

<h2>Création ou édition <small>d'une personne</small></h2>
<form class="form-group" asp-action="Edit">

    <h3>Identité <small>de la personne</small></h3>
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label for="LastName">Nom de famille</label>
                <input
                    id="LastName"
                    type="text"
                    class="form-control"
                    placeholder="Nom de famille"
                    asp-for="LastName"
                    value="@Model?.LastName" />
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label for="FirstName">Prénom</label>
                <input
                    id="FirstName"
                    type="text"
                    class="form-control"
                    placeholder="Prénom"
                    asp-for="FirstName"
                    value="@Model?.FirstName" />
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label for="DateOfBirth">Date de naissance</label>
                <input
                    id="DateOfBirth"
                    type="date"
                    class="form-control"
                    placeholder="jj/mm/aaaa"
                    asp-for="DateOfBirth" />
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label for="MobilePhone">Téléphone</label>
                <input
                    id="MobilePhone"
                    type="text"
                    class="form-control"
                    placeholder="06XXXXXXXX"
                    asp-for="PhoneNumber"
                    value="@Model?.PhoneNumber"/>
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label for="Mail">Mail</label>
                <input
                    id="Mail"
                    type="text"
                    class="form-control"
                    placeholder="email@email.com"
                    asp-for="Email"
                    value="@Model?.Email"/>
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label for="Service">Service</label>
                @Html.DropDownListFor(
                    p => p.ServiceId,
                    new SelectList(
                        _context.ServiceCollection,
                        "Id",
                        "ServiceName"
                    ),
                    "Sélectionner un service",
                    new { @class = "form-control" }
                )
            </div>
        </div>

        <div class="col-6">
            <div class="form-group">
                <label for="Roles">Rôles</label>
                @foreach(Role role in _context.RoleCollection)
                {
                    <div>
                        @Html.CheckBox(
                            role.Id.ToString(), 
                            @* Here we set checkbox check or not but I dont know how to save state *@
                            Model.PersonRoles.Where(pr => pr.RoleId == role.Id).Any()
                        )
                        @Html.Label(role.RoleName)
                    </div>
                }
            </div>
        </div>

        </div>
    </div>
        <div class="row">
            <div class="col-8">
                <button type="submit" class="btn btn-primary">Valider</button>
                <a class="btn btn-secondary" asp-action="Index">Annuler</a>
            </div>
        </div>
    </div>

</form>        

src/Isen.Dotnet.Web/Views/Person/Index.cshtml
@{
    ViewData["Title"] = "Liste des personnes";
}
@using Isen.Dotnet.Library.Model;
@model IEnumerable<Person>;
<div>
    <h1>Liste <small>des personnes</small></h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th scope="col">Date de naissance</th>
                <th scope="col">Téléphone</th>
                <th scope="col">Mail</th>
                <th scope="col">Service</th>
                <th scope="col">Rôles</th>
                <th scope="col">Action...</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var person in Model)
            {
            <tr>
                <th scope="row">@person.Id</th>
                <td>@person.LastName</td>
                <td>@person.FirstName</td>
                <td>@person.DateOfBirth.Value.ToShortDateString() (@person.Age ans)</td>
                <td>@person.PhoneNumber</td>
                <td>@person.Email</td>
                <td>@person.Service.ServiceName</td> 
                <td>@person.ToStringRoles</td>      
                <td>
                    <a class="btn btn-outline-primary"
                        asp-controller="Person"
                        asp-action="Edit"
                        asp-route-id="@person.Id">Modifier</a>
                    <a class="btn btn-outline-danger"
                        asp-controller="Person"
                        asp-action="Delete"
                        asp-route-id="@person.Id">Supprimer</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

src/Isen.Dotnet.Web/Views/Role/Edit.cshtml
@{
    ViewData["Title"] = "Edition d'un rôle";
}
@using Isen.Dotnet.Library.Model;
@model Role;

<h2>Création ou édition <small>d'un rôle</small></h2>
<form class="form-group" asp-action="Edit">

    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label for="RoleName">Nom du rôle</label>
                <input
                    id="RoleName"
                    type="text"
                    class="form-control"
                    placeholder="Nom de la ville"
                    asp-for="RoleName"
                    value="@Model?.RoleName" />
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Valider</button>
            <a class="btn btn-secondary" asp-action="Index">Annuler</a>
        </div>
    </div>

</form>        

src/Isen.Dotnet.Web/Views/Role/Index.cshtml
@{
    ViewData["Title"] = "Liste des rôles";
}
@using Isen.Dotnet.Library.Model;
@model IEnumerable<Role>;
<div>
    <h1>Liste <small>des Rôles</small></h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nom du rôle</th>         
                <th scope="col">Liste</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var role in Model)
            {
            <tr>
                <th scope="row">@role.Id</th>
                <td>@role.RoleName</td>             
                <td>
                    <a class="btn btn-outline-primary"
                        asp-controller="Role"
                        asp-action="Edit"
                        asp-route-id="@role.Id">Modifier</a>
                    <a class="btn btn-outline-danger"
                        asp-controller="Role"
                        asp-action="Delete"
                        asp-route-id="@role.Id">Supprimer</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

src/Isen.Dotnet.Web/Views/Service/Edit.cshtml
@{
    ViewData["Title"] = "Edition d'un service";
}
@using Isen.Dotnet.Library.Model;
@model Service;

<h2>Création ou édition <small>d'un service</small></h2>
<form class="form-group" asp-action="Edit">

    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label for="ServiceName">Nom</label>
                <input
                    id="ServiceName"
                    type="text"
                    class="form-control"
                    placeholder="Nom du service"
                    asp-for="ServiceName"
                    value="@Model?.ServiceName" />
            </div>
        </div>

    <div class="row">
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Valider</button>
            <a class="btn btn-secondary" asp-action="Index">Annuler</a>
        </div>
    </div>

</form>        

src/Isen.Dotnet.Web/Views/Service/Index.cshtml
@{
    ViewData["Title"] = "Liste des services";
}
@using Isen.Dotnet.Library.Model;
@model IEnumerable<Service>;
<div>
    <h1>Liste <small>des services</small></h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nom du service</th>
                <th scope="col">Action...</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var service in Model)
            {
            <tr>
                <th scope="row">@service.Id</th>
                <td>@service.ServiceName</td>
                <td>
                    <a class="btn btn-outline-primary"
                        asp-controller="Service"
                        asp-action="Edit"
                        asp-route-id="@service.Id">Modifier</a>
                    <a class="btn btn-outline-danger"
                        asp-controller="Service"
                        asp-action="Delete"
                        asp-route-id="@service.Id">Supprimer</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

src/Isen.Dotnet.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Isen.Dotnet.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <!-- Header : logo et menu -->
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Isen.Dotnet.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <!-- Menu stylé avec Bootstrap -->
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" 
                            asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" 
                                id="navbarDropdown" role="button" 
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Personnes
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" 
                                    asp-controller="Person" asp-action="Index">Toutes</a>
                                <a class="dropdown-item" 
                                    asp-controller="Person" asp-action="Edit">Nouvelle...</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" 
                                id="navbarDropdown" role="button" 
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Service
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" 
                                    asp-controller="Service" asp-action="Index">Toutes</a>
                                <a class="dropdown-item" 
                                    asp-controller="Service" asp-action="Edit">Nouvelle...</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" 
                                id="navbarDropdown" role="button" 
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Rôles
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" 
                                    asp-controller="Role" asp-action="Index">Toutes</a>
                                <a class="dropdown-item" 
                                    asp-controller="Role" asp-action="Edit">Nouvelle...</a>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- Zone de contenu -->
    <div class="container">
        <main role="main" class="pb-3">
            <!-- Razor : insère la vue ici (ex : Index.cshtml) -->
            @RenderBody()
        </main>
    </div>

    <!-- Footer : copyright, mentions légales et autres conneries -->
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Isen.Dotnet.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <!-- Insertion des librairies et scripts JS au dernier moment -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- ??? -->
    @RenderSection("Scripts", required: false)
</body>
</html>